[versions]
# LIBRARIES
# AndroidX
androidx_appcompat = "1.6.1"
androidx_constraint = "2.1.4"
androidx_core = "1.12.0"
androidx_paging = "3.2.1"
# Google
google_material = "1.11.0"
# Rx
rxjava = "2.2.21"
rxandroid = "2.1.1"
rxkotlin = "2.4.0"
# PLUGINS
agp = "7.4.2"
kotlin = "1.8.0"

[libraries]
# AndroidX
androidx-appcompat = { group = "androidx.core", name = "core-ktx", version.ref = "androidx_appcompat" }
androidx-constraint = { group = "androidx.core", name = "appcompat", version.ref = "androidx_constraint" }
androidx-core = { group = "androidx.core", name = "constraintlayout", version.ref = "androidx_core" }
androidx-paging-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "androidx_paging" }
androidx-paging-rxjava2 = { group = "androidx.paging", name = "paging-rxjava2", version.ref = "androidx_paging" }
# Google
google-material = { group = "com.google.android.material", name = "material", version.ref = "google_material" }
# Rx
rxjava-core = { group = "io.reactivex.rxjava2", name = "rxjava", version.ref = "rxjava" }
rxjava-android = { group = "io.reactivex.rxjava2", name = "rxandroid", version.ref = "rxandroid" }
rxjava-ktx = { group = "io.reactivex.rxjava2", name = "rxkotlin", version.ref = "rxkotlin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
